"""Report generation: tables, figures and the results status page.

The status page is the mechanism that keeps the paper honest between now and
submission. It is generated from what is actually in ``results/``, so a claim
without a provenance-stamped result file appears as PENDING and cannot be
quietly filled in with a plausible number.
"""

from __future__ import annotations

import json
import logging
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from .provenance import ProvenanceError, read_result

log = logging.getLogger(__name__)


@dataclass
class ClaimSpec:
    """A claim the paper wants to make, and the result file that would support it."""

    claim_id: str
    description: str
    result_file: str
    command: str
    requires_gpu: bool


# Every quantitative claim the paper intends to make. Adding a claim here without
# a corresponding result file makes it visible as PENDING rather than assumed.
CLAIMS: tuple[ClaimSpec, ...] = (
    ClaimSpec(
        "H1",
        "Distribution reduces end-to-end latency versus an equally-configured serial baseline",
        "h1_latency.json",
        "python -m maor.cli h1-latency --config configs/gpu_t1000.yaml --ablation full",
        requires_gpu=True,
    ),
    ClaimSpec(
        "H2",
        "Chunked map-reduce summarisation is non-inferior to single-pass on ECTSum ROUGE-L",
        "h2_summarisation.json",
        "python -m maor.cli h2-summarisation --config configs/gpu_t1000.yaml --n-samples 100",
        requires_gpu=True,
    ),
    ClaimSpec(
        "H3",
        "Multi-dimensional sentiment changes and improves directional recommendations",
        "h3_sentiment.json",
        "python -m maor.cli h3-sentiment",
        requires_gpu=False,
    ),
    ClaimSpec(
        "VRAM",
        "Phase-serialised execution keeps peak VRAM within the hardware budget",
        "vram_verification.json",
        "python -m maor.cli vram-verify --config configs/gpu_t1000.yaml",
        requires_gpu=True,
    ),
    ClaimSpec(
        "CHUNK",
        "ChunkFilter cost and document coverage",
        "chunk_filter_study.json",
        "python -m maor.cli chunk-filter",
        requires_gpu=False,
    ),
)


def _load(results_dir: Path, name: str) -> tuple[dict[str, Any], Any] | None:
    path = results_dir / name
    if not path.exists():
        return None
    try:
        return read_result(path)
    except (ProvenanceError, json.JSONDecodeError) as exc:
        log.warning("%s exists but is not citable: %s", path, exc)
        return None


def _hypothesis_outcomes(payload: dict[str, Any]) -> str:
    tests = payload.get("hypothesis_tests") or []
    if not tests:
        return "-"
    return ", ".join(f"{t['hypothesis_id']}={t['result']}" for t in tests)


def build_status(config: Any) -> str:
    """Render the results status page from what is on disk."""
    results_dir = Path(config.paths.results_dir)
    rows: list[str] = []
    measured = 0

    for spec in CLAIMS:
        loaded = _load(results_dir, spec.result_file)
        if loaded is None:
            status = "PENDING (GPU)" if spec.requires_gpu else "PENDING"
            rows.append(
                f"| {spec.claim_id} | {status} | — | — | `{spec.command}` |"
            )
            continue

        payload, prov = loaded
        measured += 1
        outcome = _hypothesis_outcomes(payload)
        when = (prov.timestamp_utc or "")[:10]
        commit = (prov.git_commit or "unknown")[:8]
        dirty = " (dirty)" if prov.git_dirty else ""
        rows.append(
            f"| {spec.claim_id} | MEASURED | {outcome} | {when} @ `{commit}`{dirty} "
            f"| `{spec.command}` |"
        )

    generated = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    lines = [
        "# Results status",
        "",
        "Generated by `python -m maor.cli report`. Do not edit by hand.",
        "",
        f"Last generated: {generated}",
        "",
        f"**{measured} of {len(CLAIMS)} claims have a provenance-stamped result file.**",
        "",
        "A claim with no result file is PENDING. It is not an estimate, and no number",
        "for it may appear in the paper. See `docs/EVIDENCE_POLICY.md`.",
        "",
        "| Claim | Status | Outcome | Measured | Command |",
        "|---|---|---|---|---|",
        *rows,
        "",
    ]

    # Detail sections for whatever has been measured.
    for spec in CLAIMS:
        loaded = _load(results_dir, spec.result_file)
        if loaded is None:
            continue
        payload, prov = loaded
        lines += [
            f"## {spec.claim_id} — {spec.description}",
            "",
            f"- Result file: `results/{spec.result_file}`",
            f"- Measured on: {prov.timestamp_utc} ({prov.hostname})",
            f"- Hardware: {payload.get('_hw_summary') or _describe_hw(prov)}",
            f"- Commit: `{prov.git_commit}`"
            + (" **(working tree dirty)**" if prov.git_dirty else ""),
            f"- Config SHA: `{prov.config_sha}` | seed: {prov.seed}",
            "",
        ]
        for test in payload.get("hypothesis_tests", []):
            lines.append(
                f"**{test['hypothesis_id']}: {test['result']}** — "
                f"{test['metric_name']} = {test['observed']} {test['units']} "
                f"(threshold {test['comparison']} {test['threshold']})"
            )
            if test.get("notes"):
                lines += ["", f"> {test['notes']}"]
            for warning in test.get("sanity_warnings", []):
                lines += ["", f"> **Test-design warning:** {warning}"]
            lines.append("")

        threats = payload.get("validity_threats") or []
        if threats:
            lines += ["**Validity threats carried by this result:**", ""]
            for t in threats:
                lines.append(f"- *({t['severity']})* **{t['threat']}** — {t['detail']}")
            lines.append("")

    lines += [
        "## Not measured, and why",
        "",
        "The GPU-dependent claims above are implemented and tested but unrun: the",
        "development machine has no CUDA device (Intel integrated graphics only).",
        "Producing numbers for them here would mean inventing them, which is the",
        "failure this remediation exists to correct.",
        "",
        "Follow `docs/GPU_RUNBOOK.md` on a machine with a CUDA GPU, then re-run",
        "`python -m maor.cli report` to regenerate this page.",
        "",
    ]
    return "\n".join(lines)


def _describe_hw(prov: Any) -> str:
    hw = prov.hardware or {}
    if not hw.get("has_cuda"):
        return f"CPU-only, {hw.get('cpu_count')} cores"
    gpus = hw.get("gpus") or []
    if gpus:
        g = gpus[0]
        return f"{g.get('name')} ({g.get('total_mb'):.0f} MB)"
    return "CUDA device"


def build_report(config: Any) -> int:
    """Write the status page and any tables that have data behind them."""
    results_dir = Path(config.paths.results_dir)
    docs_dir = Path(config.paths.results_dir).parent / "docs"
    docs_dir.mkdir(parents=True, exist_ok=True)
    tables_dir = Path(config.paths.tables_dir)
    tables_dir.mkdir(parents=True, exist_ok=True)

    status = build_status(config)
    status_path = docs_dir / "RESULTS_STATUS.md"
    status_path.write_text(status, encoding="utf-8")
    print(f"wrote {status_path}")

    written = 0
    h3 = _load(results_dir, "h3_sentiment.json")
    if h3:
        payload, _ = h3
        r = payload["results"]
        table = [
            "% Generated by `python -m maor.cli report`. Do not edit.",
            "\\begin{tabular}{lrr}",
            "\\toprule",
            "Metric & Scalar B3 & Multi-dimensional \\\\",
            "\\midrule",
            f"Accuracy (\\%) & {r['accuracy_b3_pct']:.2f} & {r['accuracy_multidimensional_pct']:.2f} \\\\",
            f"Macro-F1 (\\%) & {r['macro_f1_b3_pct']:.2f} & {r['macro_f1_multidimensional_pct']:.2f} \\\\",
            f"\\multicolumn{{3}}{{l}}{{Direction divergence: {r['direction_divergence_pct']:.2f}\\% "
            f"({r['n_diverged']} of {payload['n_samples']})}} \\\\",
            "\\bottomrule",
            "\\end{tabular}",
        ]
        (tables_dir / "h3_sentiment.tex").write_text("\n".join(table), encoding="utf-8")
        print(f"wrote {tables_dir / 'h3_sentiment.tex'}")
        written += 1

    chunk = _load(results_dir, "chunk_filter_study.json")
    if chunk:
        payload, _ = chunk
        rows = ["cap,n_documents,mean_chunks_after,reduction_pct_median,"
                "filter_cost_ms_median,vocabulary_retained_pct_median"]
        for entry in payload.get("cost_coverage_curve", []):
            rows.append(
                f"{entry['max_chunks']},{entry['n_documents']},"
                f"{entry['mean_chunks_after']},"
                f"{entry['reduction_pct'].get('median')},"
                f"{entry['filter_cost_ms'].get('median')},"
                f"{entry['vocabulary_retained_pct'].get('median')}"
            )
        (tables_dir / "chunk_filter_curve.csv").write_text(
            "\n".join(rows), encoding="utf-8"
        )
        print(f"wrote {tables_dir / 'chunk_filter_curve.csv'}")
        written += 1

    print(f"\n{written} table(s) generated from measured results.")
    print("Claims without a result file are listed as PENDING in RESULTS_STATUS.md.")
    return 0
